src/Entity/User.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @UniqueEntity(fields="username", message="Username already taken")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     */
    private $auto = null;

    /**
     * @ORM\Column(type="string", length=32, unique=true)
     * @Assert\NotBlank()
     * @Assert\Regex(pattern="/^[a-zA-Z0-9_]+$/")
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $role;

    /**
     * @Assert\Length(max=4096)
     * @Assert\NotBlank()
     */
    private $plainPassword;

    /**
     *
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * Pin for withdraw
     *
     * @Assert\Length(min=3, max=6)
     * @ORM\Column(type="integer", length=6)
     */
    private $pin;

    /**
     * If user is banned.
     * 0 = not banned
     * 1 = banned
     *
     * @ORM\Column(type="integer", length=1)
     */
    private $banned = 0;

    /**
     * Recover account code
     *
     * @ORM\Column(type="text")
     */
    private $recover;

    /**
     * If user has seen the recovery code.
     * 0 = not seen
     * 1 = seen
     *
     * @ORM\Column(type="integer", length=1)
     */
    private $seenRecover = 0;

    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getRoles()
    {
        return [$this->role];
    }

    public function getRole()
    {
        return $this->role;
    }

    public function setRole($role)
    {
        $this->role = $role;
    }

    public function getPin()
    {
        return $this->pin;
    }

    public function setPin($pin)
    {
        $this->pin = $pin;
    }

    public function getSalt()
    {
        return null;
    }

    public function getAuto()
    {
        return $this->auto;
    }

    public function setAuto($auto)
    {
        $this->auto = $auto;
    }

    public function getBanned()
    {
        return $this->banned;
    }

    public function setBanned($banned)
    {
        $this->banned = $banned;
    }

    public function getRecover()
    {
        return $this->recover;
    }

    public function setRecover($recover)
    {
        $this->recover = $recover;
    }

    public function getSeenRecover()
    {
        return $this->seenRecover;
    }

    public function setSeenRecover($seenRecover)
    {
        $this->seenRecover = $seenRecover;
    }

    public function eraseCredentials()
    {
        return null;
    }
}

src/Controller/Dashboard/AffiliatesController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\ReferralBalance;
use App\Form\ReferralWithdrawType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class AffiliatesController extends Controller
{

    /**
     * @Route("/affiliates/", name="affiliates")
     */
    public function affiliatesAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $profile = $this->get('App\Service\Profile')->getProfile();

        $token = $profile->getToken();

        $referralBalance = $em->getRepository(ReferralBalance::class);
        $referralBalance = $referralBalance->findOneByUsername($this->getUser()->getUsername());

        $zcash = $referralBalance->getZcashBalance();
        $monero = $referralBalance->getMoneroBalance();

        $withdrawForm = $this->createForm(ReferralWithdrawType::class);
        $withdrawForm->handleRequest($request);

        if ($withdrawForm->isSubmitted() && $withdrawForm->isValid()) {
        }

        $http = 'http';
        if (isset($_SERVER['HTTPS'])) {
            $http = 'https';
        }

        $link = $http . '://' . $_SERVER['HTTP_HOST'] . "/register/" . $token;
        return $this->render('/dashboard/shared/affiliates.html.twig', [
            'link' => $link,
            'monero' => $monero,
            'zcash' => $zcash,
            'withdrawForm' => $withdrawForm->createView(),
        ]);
    }
}

src/Controller/Dashboard/BanController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Listing;
use App\Entity\Shipping;
use App\Entity\StaffPick;
use App\Entity\User;
use App\Form\Admin\BanType;
use App\Form\Admin\StaffPickType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class BanController extends Controller
{

    /**
     * @Route("/staff/ban/", name="staffBan")
     */
    public function banAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $banForm = $this->createForm(BanType::class);
        $banForm->handleRequest($request);

        if ($banForm->isSubmitted() && $banForm->isValid()) {
            $userRepo = $em->getRepository(User::class);
            $user = $userRepo->findOneByUsername($banForm->get('username')->getData());

            if (!empty($user)) {
                $user->setBanned(1);
                $em->persist($user);

                if ($user->getRole() === 'vendor') {
                    $em = $this->getDoctrine()->getManager();
                    $listingRepo = $em->getRepository(Listing::class);
                    $listings = $listingRepo->findByUsername($user->getUsername());

                    foreach ($listings as $listing) {
                        $categoryId = $listing->getCategory();
                        $parentId = $listing->getParentCategory();

                        $em->remove($listing);

                        $shippingRepo = $em->getRepository(Shipping::class);
                        $shipping = $shippingRepo->findByListing($listing->getUuid());
                        foreach ($shipping as $single) {
                            $em->remove($single);
                        }

                        if ($listing->getStep() == 7) {
                            $this->get('App\Service\Categories')->removeItem($categoryId);
                            $this->get('App\Service\Categories')->removeItem($parentId);
                        }

                        $this->get('App\Service\ListingImages')->removeImages($listing->getUuid(), $user->getUsername());
                    }
                }
                $em->clear();
                $em->flush();

                $session = new Session();
                $session->getFlashBag()->add('error', 'This user has been banned.');
            } else {
                $session = new Session();
                $session->getFlashBag()->add('error', 'This user does not exist.');
            }

            return $this->redirectToRoute('staffBan');
        }

        return $this->render('/dashboard/admin/ban.html.twig', [
            'banForm' => $banForm->createView(),
        ]);
    }
}

src/Controller/Dashboard/CategoryController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Category;
use App\Form\Admin\CategoriesType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class CategoryController extends Controller
{

    /**
     * @Route("/staff/categories/", name="categories")
     */
    public function categoriesAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $cat[''] = '';

        foreach ($this->get('App\Service\Categories')->getCategories()['categories'] as $category) {
            $cat[$category['title']] = $category['id'];
        }

        $categoryForm = $this->createForm(CategoriesType::class, [], [
            'parent' => $cat,
        ]);
        $categoryForm->handleRequest($request);

        if ($categoryForm->isSubmitted() && $categoryForm->isValid()) {
            $categoryRepo = $em->getRepository(Category::class);
            $check = $categoryRepo->findByTitle($categoryForm->get('title')->getData());

            if (empty($categoryForm->get('parent')->getData()) && count($check) != 0) {
                $session = new Session();
                $session->getFlashBag()->add('error', 'This is a duplicate category.');
                return $this->redirectToRoute('categories');
            }

            $category = new Category();
            $category->setTitle($categoryForm->get('title')->getData());
            if (!empty($categoryForm->get('parent')->getData())) {
                $category->setParentId($categoryForm->get('parent')->getData());
                $category->setSub(0);
            }
            $em->persist($category);
            $em->flush();
            $em->clear();

            return $this->redirectToRoute('categories');
        }

        return $this->render('/dashboard/admin/categories.html.twig', [
            'categoryForm' => $categoryForm->createView(),
        ]);
    }

    /**
     * @Route("/staff/categories/delete/{id}", name="deleteCategories")
     */
    public function categoriesDeleteAction(Request $request, $id)
    {
        if ($this->getUser()->getRole() == 'admin') {
            $em = $this->getDoctrine()->getManager();

            $categoriesRepo = $em->getRepository(Category::class);
            $categories = $categoriesRepo->findOneById($id);
            $em->remove($categories);
            $em->flush();

            return $this->redirect('/staff/categories/');
        }
    }
}

src/Controller/Dashboard/DashboardController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Notification;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DashboardController extends Controller
{

    /**
     * @Route("/dashboard/{section}/", defaults={"section" = ""})
     * @Route("/dashboard/", name="dashboard")
     */
    public function dashboardAction(Request $request, $section = '')
    {
        $mesGen = $this->get('App\Service\Mailer');

        $threads = $mesGen->getUnreadThreads();

        $em = $this->getDoctrine()->getManager();
        $notificationRepo = $em->getRepository(Notification::class);
        $notifications = $notificationRepo->findByUsername($this->getUser()->getUsername(), ['id' => 'desc']);

        return $this->render('/dashboard/buyer/dashboard.html.twig', [
            'threads' => $threads,
            'notifications' => $notifications,
            'profile' => $this->get('App\Service\Profile')->getProfile(),
        ]);
    }

    /**
     * @Route("/staff/dashboard/{section}/", defaults={"section" = ""})
     * @Route("/staff/dashboard/", name="staffDashboard")
     */
    public function dashboardStaffAction(Request $request, $section = '')
    {
        $mesGen = $this->get('App\Service\Mailer');

        $threads = $mesGen->getUnreadThreads();

        return $this->render('/dashboard/admin/dashboard.html.twig', [
            'threads' => $threads,
        ]);
    }
}

src/Controller/Dashboard/DisputeController.php
<?php

namespace App\Controller\Dashboard;

use App\Entity\Notification;
use App\Entity\Orders;
use App\Entity\VendorProfile;
use App\Form\MessageType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DisputeController extends Controller
{

    /**
     * @Route("/staff/disputes/", name="staffDisputes")
     */
    public function disputesAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $status = ['vendor', 'buyer', 'disputed',];

        $orderRepo = $em->getRepository(Orders::class);

        $orders = $orderRepo->createQueryBuilder('r')
            ->select('r')
            ->where("r.status in(:status)")
            ->setParameter('status', $status, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY)
            ->orderBy('r.id', 'desc')
            ->getQuery()
            ->getArrayResult();

        return $this->render('/dashboard/admin/disputes.html.twig', [
            'orders' => $orders,
        ]);
    }

    /**
     * @Route("/staff/dispute/{uuid}/", name="staffDispute")
     */
    public function disputeAction(Request $request, $uuid)
    {
        $em = $this->getDoctrine()->getManager();

        $messageForm = $this->createForm(MessageType::class);
        $messageForm->handleRequest($request);

        $orderRepo = $em->getRepository(Orders::class);
        $order = $orderRepo->findOneByUuid($uuid);

        $mesGen = $this->get('App\Service\Mailer');

        $messages = $mesGen->getMessages($uuid);
        $thread = $mesGen->getThread($uuid);

        $profile = $this->get('App\Service\Profile')->getProfile();

        $vendorRepo = $em->getRepository(VendorProfile::class);
        $vendor = $vendorRepo->findOneByUsername($order->getVendor());

        if ($messageForm->isSubmitted() && $messageForm->isValid()) {
            $mesGen->setMessage($messageForm->get('message')->getData(), $uuid);
            $mesGen->setThreadStatus($uuid, false, false);
            return $this->redirect($request->getRequestUri());
        }

        $time = $order->getAutoDate() - time();

        $timeLeft = [
            'days' => floor($time/86400),
            'minutes' => round(($time - (floor($time/86400) * 86400))/1440, 0),
        ];

        return $this->render('/dashboard/buyer/order.html.twig', [
            'order' => $order,
            'messages' => $messages,
            'messageForm' => $messageForm->createView(),
            'edit' => $request->query->get('edit'),
            'vendor' => $vendor,
            'thread' => $thread,
            'timeLeft' => $timeLeft,
        ]);
    }

    /**
     * @Route("/staff/dispute/vendor/{id}/", name="staffDisputeVendor")
     */
    public function disputeVendorAction(Request $request, $id)
    {
        if ($this->getUser()->getRole() == 'admin') {
            $em = $this->getDoctrine()->getManager();
            $orderRepo = $em->getRepository(Orders::class);
            $order = $orderRepo->findOneBy(['uuid' => $id]);
            $order->setStatus('vendor');
            $order->setBootstrap('warning');
            $em->merge($order);
            $em->flush();
            $em->clear();

            $notification = new Notification();
            $notification->setType('refunded');
            $notification->setUsername($order->getBuyer());
            $notification->setAmount($order->getAmount());
            $notification->setBootstrap('danger');
            $notification->setTitle($order->getTitle());
            $em->persist($notification);
            $em->flush();
            $em->clear();

            $notification = new Notification();
            $notification->setType('refunded');
            $notification->setUsername($order->getVendor());
            $notification->setAmount($order->getAmount());
            $notification->setBootstrap('success');
            $notification->setTitle($order->getTitle());
            $em->persist($notification);
            $em->flush();
            $em->clear();

            return $this->redirect('/staff/dispute/' . $id . '/');
        }
    }

    /**
     * @Route("/staff/dispute/buyer/{id}/", name="staffDisputeBuyer")
     */
    public function disputeBuyerAction(Request $request, $id)
    {
        if ($this->getUser()->getRole() == 'admin') {
            $em = $this->getDoctrine()->getManager();
            $orderRepo = $em->getRepository(Orders::class);
            $order = $orderRepo->findOneBy(['uuid' => $id]);
            $order->setStatus('buyer');
            $order->setBootstrap('warning');
            $em->merge($order);
            $em->flush();
            $em->clear();

            $notification = new Notification();
            $notification->setType('refunded');
            $notification->setUsername($order->getBuyer());
            $notification->setAmount($order->getAmount());
            $notification->setBootstrap('green');
            $notification->setTitle($order->getTitle());
            $em->persist($notification);
            $em->flush();
            $em->clear();

            $notification = new Notification();
            $notification->setType('refunded');
            $notification->setUsername($order->getVendor());
            $notification->setAmount($order->getAmount());
            $notification->setBootstrap('danger');
            $notification->setTitle($order->getTitle());
            $em->persist($notification);
            $em->flush();
            $em->clear();

            return $this->redirect('/staff/dispute/' . $id . '/');
        }
    }
}

templates/dashboard/sidebar.html.twig
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-bars" aria-hidden="true"></i>&nbsp;General</h3>
    </div>
    {% set route = app.request.get('_route') %}
    {% if app.user.roles.0 == 'vendor' or app.user.roles.0 == 'buyer' %}
        <a href="/dashboard/" class="panel-block {{ route == 'dashboard' ? 'is-active' : '' }}">
            <i class="fa fa-home" aria-hidden="true"></i>&nbsp;Dashboard
        </a>
        <a href="/orders/" class="panel-block {{ route == 'orders' or route == 'order'? 'is-active' : '' }}">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;Orders
            {% if app.user.roles.0 == 'vendor' and dashboard_notifications.getNewOrderTotal() != 0 %}
                &nbsp;<div class="tag is-success">New</div>
            {% endif %}
        </a>
        <a href="/messages/" class="panel-block {{ route == 'message' or route == 'messages' or route == 'newMessage' ? 'is-active' : '' }}">
            <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Messages
            {% if dashboard_notifications.getNewMessageTotal() != 0 %}
                &nbsp;<div class="tag is-success">New</div>
            {% endif %}
        </a>
        {% if app.user.roles.0 == 'buyer' %}
            <a href="/wishlist/" class="panel-block {{ route == 'wishlist' ? 'is-active' : '' }}">
                <i class="fa fa-heart" aria-hidden="true"></i>&nbsp;Wishlist
            </a>
        {% endif %}
        <a href="/affiliates/" class="panel-block {{ route == 'affiliates' ? 'is-active' : '' }}">
            <i class="fa fa-users" aria-hidden="true"></i>&nbsp;Affiliates
        </a>
    {% endif %}
    {% if app.user.roles.0 == 'vendor' %}
        <a href="/shipping/" class="panel-block {{ route == 'shipping' or route == 'newShipping' ? 'is-active' : '' }}">
            <i class="fa fa-truck" aria-hidden="true"></i>&nbsp;Shipping
        </a>
        <a href="/listings/" class="panel-block {{ route in ['listings', 'newListing', 'tacListing', 'handleListingCategoryEdit', 'handleListingCategory', 'handleListingInfo', 'handleListingPricing',
            'handleListingShipping', 'handleListingImages', 'handleListingDescription', 'handleListingSearch', 'handleListingDiscount'] ? 'is-active' : '' }}">
            <i class="fa fa-list" aria-hidden="true"></i>&nbsp;Listings
        </a>
    {% endif %}
    {% if app.user.roles.0 == 'admin' %}
        <a href="/staff/dashboard/" class="panel-block {{ route == 'staffDashboard' ? 'is-active' : '' }}">
            <i class="fa fa-home" aria-hidden="true"></i>&nbsp;Dashboard
        </a>
        <a href="/staff/disputes/" class="panel-block {{ route == 'staffDisputes' or route == 'staffDispute' ? 'is-active' : '' }}">
            <i class="fa fa-gavel" aria-hidden="true"></i>&nbsp;Disputes
            {% if dashboard_notifications.getDisputeTotal() != 0 %}
                &nbsp;<div class="tag is-success">New</div>
            {% endif %}
        </a>
        <a href="/staff/messages/" class="panel-block {{ route == 'staffMessages' or route == 'staffMessage' or route == 'newStaffMessage' ? 'is-active' : '' }}">
            <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;Messages
            {% if dashboard_notifications.getNewMessageTotal() != 0 %}
                &nbsp;<div class="tag is-success">New</div>
            {% endif %}
        </a>
        <a href="/staff/reports/" class="panel-block {{ route == 'reports' ? 'is-active' : '' }}">
            <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;Reports
        </a>
        <a href="/staff/categories/" class="panel-block {{ route == 'categories' ? 'is-active' : '' }}">
            <i class="fa fa-folder" aria-hidden="true"></i>&nbsp;Categories
        </a>
        <a href="/staff/pick/" class="panel-block {{ route == 'staffPick' ? 'is-active' : '' }}">
            <i class="fa fa-magic" aria-hidden="true"></i>&nbsp;Staff Picks
        </a>
        <a href="/staff/ban/" class="panel-block {{ route == 'staffBan' ? 'is-active' : '' }}">
            <i class="fa fa-institution" aria-hidden="true"></i>&nbsp;Ban
        </a>
    {% endif %}
</div>
<br>
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-gears" aria-hidden="true"></i>&nbsp;Settings</h3>
    </div>
    {% if app.user.roles.0 == 'vendor' or app.user.roles.0 == 'buyer' %}
        <a href="/profile/" class="panel-block {{ route == 'profileEdit' ? 'is-active' : '' }}">
            <i class="fa fa-user" aria-hidden="true"></i>&nbsp;Profile
        </a>
        <a href="/pgp/" class="panel-block {{ route == 'pgp' ? 'is-active' : '' }}">
            <i class="fa fa-lock" aria-hidden="true"></i>&nbsp;PGP
        </a>
        <a href="/currency/" class="panel-block {{ route == 'currency' or route == 'currencyVendor' ? 'is-active' : '' }}">
            <i class="fa fa-dollar" aria-hidden="true"></i>&nbsp;Currency
        </a>
        <a href="/account/" class="panel-block {{ route == 'account' ? 'is-active' : '' }}">
            <i class="fa fa-gear" aria-hidden="true"></i>&nbsp;Account
        </a>
    {% endif %}
    {% if app.user.roles.0 == 'admin' %}
        <a href="/staff/account/" class="panel-block {{ route == 'staffAccount' ? 'is-active' : '' }}">
            <i class="fa fa-gear" aria-hidden="true"></i>&nbsp;Account
        </a>
        <a href="/staff/pgp/" class="panel-block {{ route == 'staffPGP' ? 'is-active' : '' }}">
            <i class="fa fa-lock" aria-hidden="true"></i>&nbsp;PGP
        </a>
    {% endif %}
</div>